[project]
name = "essentials"
version = "0.1.0"
description = "Exercises with essential ML libraries"
requires-python = ">=3.11"
dependencies = [
    "einops>=0.8.1",
    "jupyterlab>=4.3.5",
    "numpy>=2.2.2",
]
